// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMs_BOnfkVPm8FyaaOGt7m_QD8zHqDH_A',
    appId: '1:485573140823:web:2d9777ce45e6df70d89e12',
    messagingSenderId: '485573140823',
    projectId: 'my-notes-flutter-e8e34',
    authDomain: 'my-notes-flutter-e8e34.firebaseapp.com',
    storageBucket: 'my-notes-flutter-e8e34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AwDvAcHWDpPaOlOtj5JHIi0F76DS6-s',
    appId: '1:485573140823:android:5ad306c017e7ec4ed89e12',
    messagingSenderId: '485573140823',
    projectId: 'my-notes-flutter-e8e34',
    storageBucket: 'my-notes-flutter-e8e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOOMYSOoIleEywfedgHMgOYOBq5UYlKY',
    appId: '1:485573140823:ios:777efd03953d4862d89e12',
    messagingSenderId: '485573140823',
    projectId: 'my-notes-flutter-e8e34',
    storageBucket: 'my-notes-flutter-e8e34.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOOMYSOoIleEywfedgHMgOYOBq5UYlKY',
    appId: '1:485573140823:ios:777efd03953d4862d89e12',
    messagingSenderId: '485573140823',
    projectId: 'my-notes-flutter-e8e34',
    storageBucket: 'my-notes-flutter-e8e34.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMs_BOnfkVPm8FyaaOGt7m_QD8zHqDH_A',
    appId: '1:485573140823:web:182a70ad3b82eb1ed89e12',
    messagingSenderId: '485573140823',
    projectId: 'my-notes-flutter-e8e34',
    authDomain: 'my-notes-flutter-e8e34.firebaseapp.com',
    storageBucket: 'my-notes-flutter-e8e34.firebasestorage.app',
  );
}
